#TODO use clojure config
version: 2
default: &default
  docker:
  - image: jesiio/build-bus:latest
    environment:
      JVM_OPTS: -Xmx3200m
      DEBUG: 1
jobs:
  deps:
    <<: *default
    steps:
    - checkout
    - save_cache:
        key: source-{{ .Revision }}
        paths:
        - .git
    - restore_cache:
        key: lein-{{ checksum "project.clj" }}
    - run: lein deps
    - save_cache:
        key: lein-{{ checksum "project.clj" }}
        paths:
        - ~/.m2
    - restore_cache:
        key: npm-{{ checksum "package-dry.json" }}
    - run: dry install
    - save_cache:
        key: npm-{{ checksum "package-dry.json" }}
        paths:
        - node_modules
  deploy:
    <<: *default
    steps:
    - restore_cache:
        keys:
        - source-{{ .Revision }}
    - restore_cache:
        key: lein-{{ checksum "project.clj" }}
    - run: lein deploy clojars
  publish:
    <<: *default
    steps:
    - restore_cache:
        keys:
        - source-{{ .Revision }}
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
    - run:
        name: Publish npm package
        command: dry publish --access public
workflows:
  version: 2
  main:
    jobs:
    - deps
    - deploy:
        requires:
        - deps
        context: JESI
        filters:
          branches:
            only: master
    - publish:
        requires:
        - deps
        context: JESI
        filters:
          branches:
            only: master
