version: 2.1
default: &default
  docker:
    - image: jesiio/build-bus:latest
      user: node
aliases:
  cancel_redundant: &cancel
    run:
      name: Check & Cancel Redundant Build
      command: 'cancel-redundant-builds.sh'
  submodule: &sub
    run: git submodule update --init --recursive
jobs:
  lint:
    <<: *default
    steps:
      - *cancel
      - checkout
      - *sub
      - run: './parent.sh deps'
      - run: './parent.sh lint'
  deploy:
    <<: *default
    steps:
      - checkout
      - *sub
      - run: './parent.sh deploy'
  publish:
    <<: *default
    steps:
      - checkout
      - *sub
      - run: './parent.sh publish'
workflows:
  version: 2
  main:
    jobs:
      - lint
      - deploy:
          requires:
            - lint
          context: JESI
          filters:
            branches:
              only: master
      - publish:
          requires:
            - lint
          context: JESI
          filters:
            branches:
              only: master
