version: 2
default: &default
  docker:
  - image: jesiio/build-bus:latest
    environment:
      JVM_OPTS: -Xmx3200m
      DEBUG: 1
  steps:
  - restore_cache:
      keys:
      - source-{{ .Revision }}
jobs:
  deps:
    <<: *default
    steps:
    - checkount
    - save_cache:
        key: source-{{ .Revision }}
        paths:
        - .git
    - run: lein deps
    - save_cache:
        key: lein-{{ checksum "project.clj" }}
        paths:
        - ~/.m2
  deploy:
    <<: *default
    steps:
    - run: lein deploy clojars
  publish:
    <<: *default
    steps:
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
    - run:
        name: Publish npm package
        command: dry publish
workflows:
  version: 2
  main:
    jobs:
    - deps
    - deploy:
        requires:
        - deps
        context: JESI
        filters:
          branches:
            only: master
    - publish:
        requires:
        - deps
        context: JESI
        filters:
          branches:
            only: master
